#!/usr/bin/env bash
# recap.sh - Generate a drive session recap summary and save it to the Desktop.
#
# Pulls all task context, decisions, handoffs, and file changes from td and
# writes a structured markdown summary.
#
# Usage:
#   recap.sh [--project <name>] [--session <td-session-id>] [--output <path>]
#
# Options:
#   --project <name>        project name (default: auto-detected from git/package.json/dir)
#   --session <id>          td session ID to summarise (default: all sessions for today)
#   --output <path>         output file path (default: ~/Desktop/<project>-recap-<date>.md)
#   --dry-run               print the recap to stdout only, do not write to Desktop

set -euo pipefail

PROJECT_NAME=""
TD_SESSION=""
OUTPUT_PATH=""
DRY_RUN=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project)  PROJECT_NAME="$2"; shift 2 ;;
    --session)  TD_SESSION="$2";   shift 2 ;;
    --output)   OUTPUT_PATH="$2";  shift 2 ;;
    --dry-run)  DRY_RUN=true;      shift ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

# ---- Auto-detect project name -----------------------------------------------
detect_project_name() {
  local dir="${PWD}"
  local git_root
  git_root=$(git -C "$dir" rev-parse --show-toplevel 2>/dev/null || true)
  local search_dir="${git_root:-$dir}"

  if [[ -f "$search_dir/package.json" ]]; then
    local name
    name=$(python3 -c "import json; d=json.load(open('$search_dir/package.json')); print(d.get('name',''))" 2>/dev/null || true)
    [[ -n "$name" && "$name" != "null" ]] && echo "$name" && return
  fi

  if [[ -f "$search_dir/pyproject.toml" ]]; then
    local name
    name=$(python3 -c "
try:
    import tomllib
except ImportError:
    import tomli as tomllib
with open('$search_dir/pyproject.toml','rb') as f:
    d = tomllib.load(f)
print(d.get('project',{}).get('name','') or d.get('tool',{}).get('poetry',{}).get('name',''))
" 2>/dev/null || true)
    [[ -n "$name" && "$name" != "null" ]] && echo "$name" && return
  fi

  [[ -n "$git_root" ]] && basename "$git_root" && return
  basename "$dir"
}

[[ -z "$PROJECT_NAME" ]] && PROJECT_NAME=$(detect_project_name)

DATE=$(date '+%Y-%m-%d')
TIME=$(date '+%H:%M')
DATETIME=$(date '+%Y-%m-%d %H:%M')
SAFE_PROJECT=$(echo "$PROJECT_NAME" | tr ' /' '--')

[[ -z "$OUTPUT_PATH" ]] && OUTPUT_PATH="${HOME}/Desktop/${SAFE_PROJECT}-recap-${DATE}.md"

# ---- Collect td data --------------------------------------------------------
# All tasks (closed + in_review + any remaining open)
ALL_TASKS=$(td list 2>/dev/null || echo "(td not available)")
CLOSED_TASKS=$(td list --status closed 2>/dev/null || echo "")
REVIEW_TASKS=$(td list --status in_review 2>/dev/null || echo "")
OPEN_TASKS=$(td list --status open 2>/dev/null || echo "")
IN_PROGRESS=$(td list --status in_progress 2>/dev/null || echo "")
BLOCKED_TASKS=$(td list --status blocked 2>/dev/null || echo "")
USAGE=$(td usage -q 2>/dev/null || echo "")

# ---- Build the recap document -----------------------------------------------
generate_recap() {
cat << RECAP
# Drive Session Recap — ${PROJECT_NAME}

**Date:** ${DATETIME}
**Project:** ${PROJECT_NAME}

---

## Summary

$(td usage -q 2>/dev/null || echo "_td usage unavailable_")

---

## Completed Tasks

${CLOSED_TASKS:-_No tasks closed this session._}

---

## Submitted for Review

${REVIEW_TASKS:-_None pending review._}

---

## Still Open

${OPEN_TASKS:-_None._}

---

## In Progress (incomplete at session end)

${IN_PROGRESS:-_None._}

---

## Blocked

${BLOCKED_TASKS:-_None._}

---

## All Task Details

$(
  # For each task ID found, dump full context
  while IFS= read -r line; do
    TASK_ID=$(echo "$line" | grep -oE 'td-[a-f0-9]+' | head -1 || true)
    if [[ -n "$TASK_ID" ]]; then
      echo "### ${TASK_ID}"
      echo '```'
      td context "$TASK_ID" 2>/dev/null || echo "(no context)"
      echo '```'
      echo ""
    fi
  done <<< "$ALL_TASKS"
)

---

## Git Worktrees (if any)

$(git worktree list 2>/dev/null || echo "_Not a git repository or no worktrees._")

---

_Generated by the drive skill on ${DATETIME}_
RECAP
}

RECAP_CONTENT=$(generate_recap)

# ---- Output -----------------------------------------------------------------
if $DRY_RUN; then
  echo "$RECAP_CONTENT"
  exit 0
fi

# Ensure Desktop exists (it always should, but be safe)
mkdir -p "$(dirname "$OUTPUT_PATH")"

echo "$RECAP_CONTENT" > "$OUTPUT_PATH"

echo "Recap saved to: $OUTPUT_PATH"

# Open the file in the default app on macOS if available
if command -v open &>/dev/null; then
  open "$OUTPUT_PATH"
fi
